# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 500)
        MainWindow.setMinimumSize(QtCore.QSize(900, 500))
        MainWindow.setMaximumSize(QtCore.QSize(900, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/res/study.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 900, 430))
        self.stackedWidget.setMinimumSize(QtCore.QSize(900, 400))
        self.stackedWidget.setMaximumSize(QtCore.QSize(122222, 122222))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.labelTitle = QtWidgets.QLabel(self.page)
        self.labelTitle.setGeometry(QtCore.QRect(380, 50, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.lineEditWenku = QtWidgets.QLineEdit(self.page)
        self.lineEditWenku.setGeometry(QtCore.QRect(80, 120, 620, 30))
        self.lineEditWenku.setObjectName("lineEditWenku")
        self.pBtnDownLoad = QtWidgets.QPushButton(self.page)
        self.pBtnDownLoad.setGeometry(QtCore.QRect(710, 120, 113, 30))
        self.pBtnDownLoad.setStyleSheet("background-color: rgb(252, 2, 255);\n"
"color: rgb(255, 255, 255);")
        self.pBtnDownLoad.setObjectName("pBtnDownLoad")
        self.progressBar = QtWidgets.QProgressBar(self.page)
        self.progressBar.setGeometry(QtCore.QRect(180, 220, 550, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.labelStatus = QtWidgets.QLabel(self.page)
        self.labelStatus.setGeometry(QtCore.QRect(180, 190, 551, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelStatus.setFont(font)
        self.labelStatus.setText("")
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(410, 20, 80, 28))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_1 = QtWidgets.QLabel(self.page_2)
        self.label_1.setGeometry(QtCore.QRect(40, 70, 200, 30))
        self.label_1.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.rBtnMode1 = QtWidgets.QRadioButton(self.page_2)
        self.rBtnMode1.setGeometry(QtCore.QRect(60, 115, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rBtnMode1.setFont(font)
        self.rBtnMode1.setObjectName("rBtnMode1")
        self.rBtnMode2 = QtWidgets.QRadioButton(self.page_2)
        self.rBtnMode2.setGeometry(QtCore.QRect(60, 150, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rBtnMode2.setFont(font)
        self.rBtnMode2.setObjectName("rBtnMode2")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(40, 250, 200, 140))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(200, 140))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(153, 153, 153);")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.pBtnSetPath = QtWidgets.QPushButton(self.page_2)
        self.pBtnSetPath.setGeometry(QtCore.QRect(400, 130, 113, 30))
        self.pBtnSetPath.setStyleSheet("background-color: rgb(252, 2, 255);\n"
"color: rgb(255, 255, 255);")
        self.pBtnSetPath.setObjectName("pBtnSetPath")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(350, 70, 200, 30))
        self.label_3.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.labelAbout = QtWidgets.QLabel(self.page_2)
        self.labelAbout.setGeometry(QtCore.QRect(280, 250, 580, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAbout.sizePolicy().hasHeightForWidth())
        self.labelAbout.setSizePolicy(sizePolicy)
        self.labelAbout.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelAbout.setFont(font)
        self.labelAbout.setStyleSheet("color: rgb(153, 153, 153);")
        self.labelAbout.setWordWrap(True)
        self.labelAbout.setObjectName("labelAbout")
        self.labelAboutLink = QtWidgets.QLabel(self.page_2)
        self.labelAboutLink.setGeometry(QtCore.QRect(280, 350, 571, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelAboutLink.sizePolicy().hasHeightForWidth())
        self.labelAboutLink.setSizePolicy(sizePolicy)
        self.labelAboutLink.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelAboutLink.setFont(font)
        self.labelAboutLink.setStyleSheet("color: rgb(153, 153, 153);")
        self.labelAboutLink.setWordWrap(True)
        self.labelAboutLink.setObjectName("labelAboutLink")
        self.pBtnAbout = QtWidgets.QPushButton(self.page_2)
        self.pBtnAbout.setGeometry(QtCore.QRect(670, 130, 113, 30))
        self.pBtnAbout.setStyleSheet("background-color: rgb(252, 2, 255);\n"
"color: rgb(255, 255, 255);")
        self.pBtnAbout.setObjectName("pBtnAbout")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 44))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.QAction_homepage = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/res/homepage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QAction_homepage.setIcon(icon1)
        self.QAction_homepage.setObjectName("QAction_homepage")
        self.QAction_setting = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/res/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QAction_setting.setIcon(icon2)
        self.QAction_setting.setObjectName("QAction_setting")
        self.QAction_exit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/res/tuichu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.QAction_exit.setIcon(icon3)
        self.QAction_exit.setObjectName("QAction_exit")
        self.toolBar.addAction(self.QAction_homepage)
        self.toolBar.addAction(self.QAction_setting)
        self.toolBar.addAction(self.QAction_exit)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.pBtnDownLoad.clicked.connect(MainWindow.download)
        self.QAction_homepage.triggered.connect(MainWindow.homepage)
        self.QAction_setting.triggered.connect(MainWindow.setting)
        self.rBtnMode1.clicked.connect(MainWindow.selectDownloadMode)
        self.rBtnMode2.clicked.connect(MainWindow.selectDownloadMode)
        self.QAction_exit.triggered.connect(MainWindow.close)
        self.pBtnSetPath.clicked.connect(MainWindow.setDownloadPath)
        self.pBtnAbout.clicked.connect(MainWindow.about)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "冰冰文库"))
        self.labelTitle.setText(_translate("MainWindow", "百度文库下载器"))
        self.lineEditWenku.setPlaceholderText(_translate("MainWindow", "请输入百度文库链接"))
        self.pBtnDownLoad.setText(_translate("MainWindow", "下载"))
        self.label.setText(_translate("MainWindow", "设置中心"))
        self.label_1.setText(_translate("MainWindow", "一、百度文库下载方式选择"))
        self.rBtnMode1.setText(_translate("MainWindow", "方式一（格式为主）"))
        self.rBtnMode2.setText(_translate("MainWindow", "方式二（内容为主）"))
        self.label_2.setText(_translate("MainWindow", "说明：\n"
"1.方式一：与原文样式基本一致，保存为txt/pdf文件。(不支持付费文档)\n"
"2.方式二：主要以获取内容为主（文字与图片），保存为txt/doc/ppt/pdf文件。"))
        self.pBtnSetPath.setText(_translate("MainWindow", "更改下载目录"))
        self.label_3.setText(_translate("MainWindow", "二、更改百度文库默认下载目录"))
        self.labelAbout.setText(_translate("MainWindow", "声明：\n"
"1.严禁用于商业用途，如有侵权，请告之删除。\n"
"2.本程序(下载方式一)主要是将M010K的GitHub项目BaiduWenkuSpider界面化，并作适当修改。"))
        self.labelAboutLink.setText(_translate("MainWindow", "链接："))
        self.pBtnAbout.setText(_translate("MainWindow", "关于"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.QAction_homepage.setText(_translate("MainWindow", "首页"))
        self.QAction_homepage.setToolTip(_translate("MainWindow", "打开首页"))
        self.QAction_setting.setText(_translate("MainWindow", "设置"))
        self.QAction_setting.setToolTip(_translate("MainWindow", "打开设置"))
        self.QAction_exit.setText(_translate("MainWindow", "退出"))
        self.QAction_exit.setToolTip(_translate("MainWindow", "退出程序"))

import res_rc
